-- Import the original Forno workbook catalog and secure Admin-only metadata changes.

create unique index if not exists suppliers_name_ci_key on public.suppliers (lower(name));

insert into public.departments (name, sort_order) values
  ('Frutas y verduras', 10),
  ('Carnes y embutidos', 20),
  ('Vinos', 60),
  ('Otras bebidas', 70),
  ('Otros', 99)
on conflict (name) do update set sort_order = excluded.sort_order;

insert into public.suppliers (name) values
  ('Butcher'),
  ('Cristal'),
  ('CZ'),
  ('DD'),
  ('Diaco Food'),
  ('Disal'),
  ('El Roble'),
  ('GYG'),
  ('Hielo Polar'),
  ('Kreef'),
  ('La Constancia'),
  ('Lactolac'),
  ('Legumes'),
  ('Lucania'),
  ('Mercado'),
  ('Molsa'),
  ('Optimun Coffee'),
  ('Pepsi'),
  ('Premier'),
  ('PriceSmart'),
  ('Selectos'),
  ('Super'),
  ('Viva Espresso'),
  ('Winco')
on conflict (lower(name)) do update set active = true;

with source as (
  select * from jsonb_to_recordset(
    '[
  {
    "sku": "XLS-FV-004",
    "name": "Sandia",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 7,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-005",
    "name": "Piña",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 6,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-006",
    "name": "Papaya",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 6,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-007",
    "name": "Fresa",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.5,
    "par_level": 3.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-008",
    "name": "Banano",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 20,
    "par_level": 35,
    "reorder_point": 10,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-009",
    "name": "Limones",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 10,
    "par_level": 110,
    "reorder_point": 33,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-010",
    "name": "Platanos",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 3.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-011",
    "name": "Melon",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-012",
    "name": "Peras",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-013",
    "name": "Blueberries",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 800,
    "par_level": 800,
    "reorder_point": 240,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-014",
    "name": "Naranajas",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 10,
    "par_level": 10,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-015",
    "name": "Albahaca",
    "department": "Frutas y verduras",
    "supplier": "Legumes",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0.5,
    "par_level": 2.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-016",
    "name": "Arugula (Specifically Sourced)",
    "department": "Frutas y verduras",
    "supplier": "Legumes",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0.8,
    "par_level": 5.8,
    "reorder_point": 1.7,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-017",
    "name": "Tomate Cherry",
    "department": "Frutas y verduras",
    "supplier": "Legumes",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-018",
    "name": "Flores de pensamiento",
    "department": "Frutas y verduras",
    "supplier": "Legumes",
    "base_unit": "caja",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-019",
    "name": "Hongo Champiñon",
    "department": "Frutas y verduras",
    "supplier": "Legumes",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-020",
    "name": "Tomate de cocina",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 8,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-021",
    "name": "Jalapeño",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": 0.5,
    "package_unit": "lb",
    "quantity": 1,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-022",
    "name": "Cebollas Blancas",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-023",
    "name": "Chile verde",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-024",
    "name": "Loroco",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-025",
    "name": "Ajos",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "cabeza",
    "package_size": null,
    "package_unit": null,
    "quantity": 30,
    "par_level": 30,
    "reorder_point": 9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-026",
    "name": "Cebolla Morada",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.5,
    "par_level": 3.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-027",
    "name": "Zanahoria",
    "department": "Frutas y verduras",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-028",
    "name": "Morrones",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-029",
    "name": "Hongo Ostra",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-030",
    "name": "Alcaparra",
    "department": "Frutas y verduras",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2.5,
    "par_level": 2.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-031",
    "name": "Chile habanero",
    "department": "Frutas y verduras",
    "supplier": "Selectos",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 10,
    "par_level": 10.2,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-032",
    "name": "Menta",
    "department": "Frutas y verduras",
    "supplier": "Selectos",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 15,
    "par_level": 15,
    "reorder_point": 4,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-033",
    "name": "Zuchinni",
    "department": "Frutas y verduras",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-034",
    "name": "Apio",
    "department": "Frutas y verduras",
    "supplier": "Selectos",
    "base_unit": "unidad",
    "package_size": 0.5,
    "package_unit": "lb",
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-035",
    "name": "Peperonchinos",
    "department": "Frutas y verduras",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-036",
    "name": "Aguacate",
    "department": "Frutas y verduras",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-037",
    "name": "Repollo Morado",
    "department": "Frutas y verduras",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-FV-038",
    "name": "Perejil",
    "department": "Frutas y verduras",
    "supplier": null,
    "base_unit": "manojo",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-004",
    "name": "Tocino",
    "department": "Carnes y embutidos",
    "supplier": "Butcher",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.5,
    "par_level": 5.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-005",
    "name": "Panceta de Cerdo",
    "department": "Carnes y embutidos",
    "supplier": "Butcher",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-006",
    "name": "Salami",
    "department": "Carnes y embutidos",
    "supplier": "CZ",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 5,
    "par_level": 2.9,
    "reorder_point": 0.9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-007",
    "name": "Villani Prosciutto Pastorelo",
    "department": "Carnes y embutidos",
    "supplier": "CZ",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 7,
    "par_level": 16.2,
    "reorder_point": 4.9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-008",
    "name": "Jamon desayuno",
    "department": "Carnes y embutidos",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 7,
    "par_level": 9,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-009",
    "name": "Chorizo de tuza",
    "department": "Carnes y embutidos",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 4,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-010",
    "name": "Chorizo Argentino",
    "department": "Carnes y embutidos",
    "supplier": null,
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-011",
    "name": "Salchica de Hot dog",
    "department": "Carnes y embutidos",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 6,
    "par_level": 7,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-012",
    "name": "Carne para Phyli",
    "department": "Carnes y embutidos",
    "supplier": null,
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-ME-013",
    "name": "Pechuga de pollo",
    "department": "Carnes y embutidos",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-004",
    "name": "Belnero Toscana IGT",
    "department": "Vinos",
    "supplier": "Disal",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-005",
    "name": "UNADIR",
    "department": "Vinos",
    "supplier": "GYG",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 7,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-006",
    "name": "Lengua Azul Blend",
    "department": "Vinos",
    "supplier": "GYG",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 6,
    "par_level": 6,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-007",
    "name": "Santa Margarita Chianti Classico",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-008",
    "name": "Gerard Bertrand Pinot Noir",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-009",
    "name": "Crane Lake Red Blend",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-010",
    "name": "3 Passo Rosso",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-011",
    "name": "Chapputier Marius Rouque",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-012",
    "name": "Santa Margarita Veneto, Merlot",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-013",
    "name": "Pasqua Passionestimento",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-014",
    "name": "Ramon Bilbao Reserva",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-015",
    "name": "Ramon Bilbao Crianza",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-016",
    "name": "Santa Margarita Pinot Grigio",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-017",
    "name": "Gerard Bertrand Sauvignon Blanc",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-018",
    "name": "Crane Lake Sauvignon Blac",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-019",
    "name": "3 Passo Bianco",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 4,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-020",
    "name": "Casa Defra Pinot Grigio",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-021",
    "name": "Chapoutier Marius Blanc",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-022",
    "name": "Gerard Bertrand Rose",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-023",
    "name": "Crane Lake White Zinfandel",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-024",
    "name": "Chapoutier  Marius Rose",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-025",
    "name": "Saint Louis",
    "department": "Vinos",
    "supplier": "Disal",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 6,
    "par_level": 18,
    "reorder_point": 5,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-026",
    "name": "Charles Roux Blanc de Blancs Brut",
    "department": "Vinos",
    "supplier": "Premier",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-WI-027",
    "name": "Cielo 0% alcohol",
    "department": "Vinos",
    "supplier": "Winco",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-004",
    "name": "Pilsener",
    "department": "Otras bebidas",
    "supplier": "La Constancia",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 49,
    "par_level": 73,
    "reorder_point": 21,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-005",
    "name": "Suprema",
    "department": "Otras bebidas",
    "supplier": "Pepsi",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 16,
    "par_level": 64,
    "reorder_point": 19,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-006",
    "name": "Cerveza Peroni",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 48,
    "par_level": 72,
    "reorder_point": 21,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-007",
    "name": "Limoncello",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-008",
    "name": "Licor 43",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-009",
    "name": "GIN",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-010",
    "name": "Aperol",
    "department": "Otras bebidas",
    "supplier": "PriceSmart",
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-011",
    "name": "Vermut Rosso",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-012",
    "name": "Campari",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-013",
    "name": "Ron Cihuatan Indigo",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1095,
    "par_level": 1097,
    "reorder_point": 329,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-014",
    "name": "Tic Tack",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-015",
    "name": "Disaronno Amaretto",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-016",
    "name": "Regia 750ml",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 12,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-017",
    "name": "Garrafon de agua Cristal",
    "department": "Otras bebidas",
    "supplier": "Cristal",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-018",
    "name": "Jugo de naranja",
    "department": "Otras bebidas",
    "supplier": "Diaco Food",
    "base_unit": "galon",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 9,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-019",
    "name": "Hielo",
    "department": "Otras bebidas",
    "supplier": "Hielo Polar",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 5,
    "par_level": 19,
    "reorder_point": 5,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-020",
    "name": "Coca Cola",
    "department": "Otras bebidas",
    "supplier": "La Constancia",
    "base_unit": "lata",
    "package_size": null,
    "package_unit": null,
    "quantity": 13,
    "par_level": 37,
    "reorder_point": 11,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-021",
    "name": "Fresca",
    "department": "Otras bebidas",
    "supplier": "La Constancia",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 5,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-022",
    "name": "Aqua (pepsi) 750ml",
    "department": "Otras bebidas",
    "supplier": "Pepsi",
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 15,
    "par_level": 15,
    "reorder_point": 4,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-023",
    "name": "Acqua Panna 1L.",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 9,
    "par_level": 9,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-024",
    "name": "Acqua Panna 500ml",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-025",
    "name": "San Pelegrino 500ml",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 23,
    "par_level": 47,
    "reorder_point": 14,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-026",
    "name": "S. Pelegrino Natural Fico de India",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 17,
    "par_level": 17,
    "reorder_point": 5,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-027",
    "name": "S. Pelegrino Natural Arranciata",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 12,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-028",
    "name": "S. Pelegrino Zero Pomegrande Orange",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 6,
    "par_level": 18,
    "reorder_point": 5,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-029",
    "name": "S. Pelegrino Zero Bloom Orange",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 12,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-030",
    "name": "Salutaris cocteleria",
    "department": "Otras bebidas",
    "supplier": "Pepsi",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 9,
    "par_level": 33,
    "reorder_point": 9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-031",
    "name": "Agua tonica",
    "department": "Otras bebidas",
    "supplier": "Premier",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 19,
    "par_level": 19,
    "reorder_point": 5,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-032",
    "name": "Leche Deslactosada",
    "department": "Otras bebidas",
    "supplier": "PriceSmart",
    "base_unit": "carton",
    "package_size": null,
    "package_unit": null,
    "quantity": 8,
    "par_level": 9,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-033",
    "name": "Leche de Avena",
    "department": "Otras bebidas",
    "supplier": "PriceSmart",
    "base_unit": "carton",
    "package_size": null,
    "package_unit": null,
    "quantity": 4,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-034",
    "name": "Leche de almendras",
    "department": "Otras bebidas",
    "supplier": "PriceSmart",
    "base_unit": "carton",
    "package_size": null,
    "package_unit": null,
    "quantity": 8,
    "par_level": 8,
    "reorder_point": 2,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-035",
    "name": "Pilsener",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 50,
    "par_level": 50,
    "reorder_point": 15,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-036",
    "name": "Suprema",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 18,
    "par_level": 18,
    "reorder_point": 5,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-037",
    "name": "Peroni",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 60,
    "par_level": 60,
    "reorder_point": 18,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-038",
    "name": "Regia 700ml",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-039",
    "name": "Coca cola Lata",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-040",
    "name": "Fresca",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-041",
    "name": "Coca cola Vidrio",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 20,
    "par_level": 20,
    "reorder_point": 6,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-042",
    "name": "Deslactosada",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "carton",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-043",
    "name": "Avena",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "carton",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-044",
    "name": "Almendra",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "carton",
    "package_size": null,
    "package_unit": null,
    "quantity": 5,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-045",
    "name": "Aqua Panna 1L",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-046",
    "name": "Aqua Panna 500ml",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-047",
    "name": "Pepsi aqua 700ml",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 12,
    "par_level": 12,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-048",
    "name": "Pepsi aqua 500ml",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-049",
    "name": "Desechables",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-050",
    "name": "Cajas de pizza grande",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-051",
    "name": "Cajas de pizza pequeñas",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 50,
    "par_level": 50,
    "reorder_point": 15,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-052",
    "name": "Desechables negros para llevar",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 12,
    "par_level": 12,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-053",
    "name": "Vasos de cristal 16 onz",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-054",
    "name": "Tapas de cristal 16 onz",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 75,
    "par_level": 75,
    "reorder_point": 22,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-055",
    "name": "Vasos craft de 8onz",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 75,
    "par_level": 75,
    "reorder_point": 22,
    "unit_cost": 0
  },
  {
    "sku": "XLS-BE-056",
    "name": "Tapas de vaso 8onz",
    "department": "Otras bebidas",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 125,
    "par_level": 125,
    "reorder_point": 37,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-004",
    "name": "Aceite de Oliva",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 3.5,
    "par_level": 2.6,
    "reorder_point": 0.8,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-005",
    "name": "Aceite Vegetal",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "barril",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-006",
    "name": "Aceite de trufa",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 13,
    "par_level": 13,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-007",
    "name": "Vinagre Blanco",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "galon",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-008",
    "name": "Vinagre Valsamico",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 29,
    "par_level": 29,
    "reorder_point": 8,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-009",
    "name": "Salsa de tomate para pizza",
    "department": "Otros",
    "supplier": null,
    "base_unit": "lata",
    "package_size": null,
    "package_unit": null,
    "quantity": 5,
    "par_level": 11,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-010",
    "name": "Divella Aglio olio e peperoncino",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-011",
    "name": "Aceitunas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-012",
    "name": "Café molido drip",
    "department": "Otros",
    "supplier": "Viva Espresso",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 15,
    "par_level": 25,
    "reorder_point": 7,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-013",
    "name": "Café en grano Geisha",
    "department": "Otros",
    "supplier": "Optimun Coffee",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 13,
    "par_level": 13,
    "reorder_point": 3,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-014",
    "name": "Frijoles molidos desayuno",
    "department": "Otros",
    "supplier": null,
    "base_unit": "paquete",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-015",
    "name": "Chispas de Chocolate",
    "department": "Otros",
    "supplier": "El Roble",
    "base_unit": "unidad",
    "package_size": 0.5,
    "package_unit": "lb",
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-016",
    "name": "Azucar Glass",
    "department": "Otros",
    "supplier": "El Roble",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-017",
    "name": "Azucar",
    "department": "Otros",
    "supplier": "El Roble",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 10,
    "par_level": 20,
    "reorder_point": 6,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-018",
    "name": "Miel",
    "department": "Otros",
    "supplier": "Mercado",
    "base_unit": "botella",
    "package_size": null,
    "package_unit": null,
    "quantity": 2.5,
    "par_level": 5.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-019",
    "name": "Chia",
    "department": "Otros",
    "supplier": "Super",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.5,
    "par_level": 1.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-020",
    "name": "Aceite en areosol",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "bote",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-021",
    "name": "Granola",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "bolsa",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-022",
    "name": "Nutella",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "galon",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-023",
    "name": "Sobrecito de azucar",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "bolsa",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-024",
    "name": "Splenda",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "caja",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-025",
    "name": "Sobres de sal",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "bolsa",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-026",
    "name": "Semillas de girasol",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.2,
    "par_level": 1.2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-027",
    "name": "Almendras",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-028",
    "name": "Pecanas",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.2,
    "par_level": 3.2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-029",
    "name": "Sal gruesa Cocina",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-030",
    "name": "Sal fina",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-031",
    "name": "Soya",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "ml",
    "package_size": null,
    "package_unit": null,
    "quantity": 300,
    "par_level": 300,
    "reorder_point": 90,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-032",
    "name": "Mantequilla de mani",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 1130,
    "par_level": 1130,
    "reorder_point": 339,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-033",
    "name": "Miel de Maple",
    "department": "Otros",
    "supplier": "Selectos",
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-034",
    "name": "Harina Fuerte",
    "department": "Otros",
    "supplier": "Molsa",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 30,
    "par_level": 30,
    "reorder_point": 9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-035",
    "name": "Harina Suave",
    "department": "Otros",
    "supplier": "Molsa",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 30,
    "par_level": 30,
    "reorder_point": 9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-036",
    "name": "Levadura Fresca",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 300,
    "par_level": 300,
    "reorder_point": 90,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-037",
    "name": "Queso manchego",
    "department": "Otros",
    "supplier": "Kreef",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.5,
    "par_level": 1.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-038",
    "name": "Queso Grutier",
    "department": "Otros",
    "supplier": "Kreef",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-039",
    "name": "Queso de Cabra con vino",
    "department": "Otros",
    "supplier": "Kreef",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-040",
    "name": "Mantequilla",
    "department": "Otros",
    "supplier": "Lactolac",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 3,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-041",
    "name": "Queso Mozzarella desayuno",
    "department": "Otros",
    "supplier": "Lactolac",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 2.5,
    "par_level": 3.5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-042",
    "name": "Huevos",
    "department": "Otros",
    "supplier": "Mercado",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 210,
    "par_level": 360,
    "reorder_point": 108,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-043",
    "name": "Crema",
    "department": "Otros",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1.23,
    "par_level": 1.23,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-044",
    "name": "Queso Fresco",
    "department": "Otros",
    "supplier": "Mercado",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 3,
    "par_level": 5,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-045",
    "name": "Mozzarella Fresca",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 4.5,
    "par_level": 14.5,
    "reorder_point": 4,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-046",
    "name": "Mozzarella fresca en revanado",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-047",
    "name": "Queso Feta",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 300,
    "par_level": 300,
    "reorder_point": 90,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-048",
    "name": "Yourgurt griego",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "bote",
    "package_size": null,
    "package_unit": null,
    "quantity": 4,
    "par_level": 6,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-049",
    "name": "Parmesano",
    "department": "Otros",
    "supplier": "PriceSmart",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 4.2,
    "par_level": 4.2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-050",
    "name": "Helado de vainilla",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-051",
    "name": "Queso Mascarpone",
    "department": "Otros",
    "supplier": "Lucania",
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-052",
    "name": "Dolce vita",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-053",
    "name": "Tiramisu",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-054",
    "name": "Canolis",
    "department": "Otros",
    "supplier": null,
    "base_unit": "orden",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-055",
    "name": "Galletas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-056",
    "name": "Banana Bread",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-057",
    "name": "Tostada Dorata",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-058",
    "name": "Pasta larga",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-059",
    "name": "Vasos de 8 onz",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 125,
    "par_level": 125,
    "reorder_point": 37,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-060",
    "name": "Tapas de 8onz",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 175,
    "par_level": 175,
    "reorder_point": 52,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-061",
    "name": "Vasos de 12 onz",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-062",
    "name": "Tapas de 12 onz",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-063",
    "name": "Vasos de cristal 16onz",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 35,
    "par_level": 135,
    "reorder_point": 40,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-064",
    "name": "Tapas domo cristal 16onz",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 35,
    "par_level": 35,
    "reorder_point": 10,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-065",
    "name": "Cajas de pizza x medida",
    "department": "Otros",
    "supplier": "DD",
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 50,
    "reorder_point": 15,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-066",
    "name": "Litros",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 4,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-067",
    "name": "Medios Litros",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-068",
    "name": "Octavos o pintas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-069",
    "name": "Cajas de pizza pequeñas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 27,
    "par_level": 77,
    "reorder_point": 23,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-070",
    "name": "Ali Oli Trufa",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-071",
    "name": "Pesto",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-072",
    "name": "Salsa de pizza",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-073",
    "name": "Stracciatella",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-074",
    "name": "Tomates deshidratado",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-075",
    "name": "Zuchinni",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-076",
    "name": "Tomates enlatados para salsa",
    "department": "Otros",
    "supplier": null,
    "base_unit": "lata",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-077",
    "name": "Morrones asados",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-078",
    "name": "Peras Caramelizadas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-079",
    "name": "Peras cortadas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-080",
    "name": "Piña Dorada para pizza",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-081",
    "name": "Pecanas para pizza o ensalada",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-082",
    "name": "Mozarella procesada",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-083",
    "name": "Salami",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 2.9,
    "reorder_point": 0.9,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-084",
    "name": "Tocino procesado para pizza",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-085",
    "name": "Prosciutto procesado",
    "department": "Otros",
    "supplier": null,
    "base_unit": "g",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-086",
    "name": "Parmesano cortado",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-087",
    "name": "Cebolla caramelizada",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-088",
    "name": "Mantequilla de ajo",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-089",
    "name": "Miel picante",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-090",
    "name": "Vinagreta",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-091",
    "name": "Reduccion Balsamica",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-092",
    "name": "Focaccia",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-093",
    "name": "Butter Milk bread",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-094",
    "name": "Mantequilla de mani",
    "department": "Otros",
    "supplier": null,
    "base_unit": "bote",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-095",
    "name": "Miel de Maple",
    "department": "Otros",
    "supplier": null,
    "base_unit": "bote",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-096",
    "name": "Frijoles con chorizo",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 2,
    "par_level": 2,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-097",
    "name": "Sofrito de tomate",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 1,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-098",
    "name": "Leche para tostadas",
    "department": "Otros",
    "supplier": null,
    "base_unit": "l",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-099",
    "name": "Queso Provolone",
    "department": "Otros",
    "supplier": null,
    "base_unit": "lb",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 1,
    "reorder_point": 1,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-100",
    "name": "Vinagre de arroz",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-101",
    "name": "Salsa soya",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-102",
    "name": "Salsa de ostras",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-103",
    "name": "Vinagre de manzana",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-104",
    "name": "Ketchup",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  },
  {
    "sku": "XLS-OT-105",
    "name": "Salsa Inglesa",
    "department": "Otros",
    "supplier": null,
    "base_unit": "unidad",
    "package_size": null,
    "package_unit": null,
    "quantity": 0,
    "par_level": 0,
    "reorder_point": 0,
    "unit_cost": 0
  }
]'::jsonb
  ) as x(
    sku text,
    name text,
    department text,
    supplier text,
    base_unit text,
    quantity numeric,
    par_level numeric,
    reorder_point numeric,
    unit_cost numeric,
    package_size numeric,
    package_unit text
  )
)
insert into public.inventory_items (
  sku, name, department_id, supplier_id, base_unit, quantity, par_level,
  reorder_point, unit_cost, package_size, package_unit, active
)
select
  source.sku, source.name, departments.id, suppliers.id, source.base_unit,
  source.quantity, source.par_level, source.reorder_point, source.unit_cost,
  source.package_size, source.package_unit, true
from source
join public.departments on departments.name = source.department
left join public.suppliers on lower(suppliers.name) = lower(source.supplier)
on conflict (sku) do update set
  name = excluded.name,
  department_id = excluded.department_id,
  supplier_id = excluded.supplier_id,
  base_unit = excluded.base_unit,
  quantity = excluded.quantity,
  par_level = excluded.par_level,
  reorder_point = excluded.reorder_point,
  unit_cost = excluded.unit_cost,
  package_size = excluded.package_size,
  package_unit = excluded.package_unit,
  active = true,
  updated_at = now();

-- Catalog metadata is read-only for Local users. Quantity changes will move through
-- audited stock movement functions in the next inventory slice.
drop policy if exists "staff update inventory" on public.inventory_items;
drop policy if exists "admins update inventory" on public.inventory_items;
create policy "admins update inventory"
  on public.inventory_items for update to authenticated
  using (public.is_admin()) with check (public.is_admin());
